//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// Este código fuente fue generado automáticamente por xsd, Versión=4.8.3928.0.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class factura {
    
    private infoTributaria infoTributariaField;
    
    private facturaInfoFactura infoFacturaField;
    
    private facturaDetalle[] detallesField;
    
    private reembolsosReembolsoDetalle[] reembolsosField;
    
    private tipoNegociable tipoNegociableField;
    
    private maquinaFiscal maquinaFiscalField;
    
    private facturaCampoAdicional[] infoAdicionalField;
    
    private SignatureType signatureField;
    
    private facturaID idField;
    
    private bool idFieldSpecified;
    
    private string versionField;
    
    /// <remarks/>
    public infoTributaria infoTributaria {
        get {
            return this.infoTributariaField;
        }
        set {
            this.infoTributariaField = value;
        }
    }
    
    /// <remarks/>
    public facturaInfoFactura infoFactura {
        get {
            return this.infoFacturaField;
        }
        set {
            this.infoFacturaField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("detalle", IsNullable=false)]
    public facturaDetalle[] detalles {
        get {
            return this.detallesField;
        }
        set {
            this.detallesField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("reembolsoDetalle", IsNullable=false)]
    public reembolsosReembolsoDetalle[] reembolsos {
        get {
            return this.reembolsosField;
        }
        set {
            this.reembolsosField = value;
        }
    }
    
    /// <remarks/>
    public tipoNegociable tipoNegociable {
        get {
            return this.tipoNegociableField;
        }
        set {
            this.tipoNegociableField = value;
        }
    }
    
    /// <remarks/>
    public maquinaFiscal maquinaFiscal {
        get {
            return this.maquinaFiscalField;
        }
        set {
            this.maquinaFiscalField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("campoAdicional", IsNullable=false)]
    public facturaCampoAdicional[] infoAdicional {
        get {
            return this.infoAdicionalField;
        }
        set {
            this.infoAdicionalField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.w3.org/2000/09/xmldsig#")]
    public SignatureType Signature {
        get {
            return this.signatureField;
        }
        set {
            this.signatureField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public facturaID id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool idSpecified {
        get {
            return this.idFieldSpecified;
        }
        set {
            this.idFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string version {
        get {
            return this.versionField;
        }
        set {
            this.versionField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class infoTributaria {
    
    private string ambienteField;
    
    private string tipoEmisionField;
    
    private string razonSocialField;
    
    private string nombreComercialField;
    
    private string rucField;
    
    private string claveAccesoField;
    
    private string codDocField;
    
    private string estabField;
    
    private string ptoEmiField;
    
    private string secuencialField;
    
    private string dirMatrizField;
    
    private string agenteRetencionField;
    
    private string contribuyenteRimpeField;
    
    /// <remarks/>
    public string ambiente {
        get {
            return this.ambienteField;
        }
        set {
            this.ambienteField = value;
        }
    }
    
    /// <remarks/>
    public string tipoEmision {
        get {
            return this.tipoEmisionField;
        }
        set {
            this.tipoEmisionField = value;
        }
    }
    
    /// <remarks/>
    public string razonSocial {
        get {
            return this.razonSocialField;
        }
        set {
            this.razonSocialField = value;
        }
    }
    
    /// <remarks/>
    public string nombreComercial {
        get {
            return this.nombreComercialField;
        }
        set {
            this.nombreComercialField = value;
        }
    }
    
    /// <remarks/>
    public string ruc {
        get {
            return this.rucField;
        }
        set {
            this.rucField = value;
        }
    }
    
    /// <remarks/>
    public string claveAcceso {
        get {
            return this.claveAccesoField;
        }
        set {
            this.claveAccesoField = value;
        }
    }
    
    /// <remarks/>
    public string codDoc {
        get {
            return this.codDocField;
        }
        set {
            this.codDocField = value;
        }
    }
    
    /// <remarks/>
    public string estab {
        get {
            return this.estabField;
        }
        set {
            this.estabField = value;
        }
    }
    
    /// <remarks/>
    public string ptoEmi {
        get {
            return this.ptoEmiField;
        }
        set {
            this.ptoEmiField = value;
        }
    }
    
    /// <remarks/>
    public string secuencial {
        get {
            return this.secuencialField;
        }
        set {
            this.secuencialField = value;
        }
    }
    
    /// <remarks/>
    public string dirMatriz {
        get {
            return this.dirMatrizField;
        }
        set {
            this.dirMatrizField = value;
        }
    }
    
    /// <remarks/>
    public string agenteRetencion {
        get {
            return this.agenteRetencionField;
        }
        set {
            this.agenteRetencionField = value;
        }
    }
    
    /// <remarks/>
    public string contribuyenteRimpe {
        get {
            return this.contribuyenteRimpeField;
        }
        set {
            this.contribuyenteRimpeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.w3.org/2000/09/xmldsig#")]
[System.Xml.Serialization.XmlRootAttribute("Object", Namespace="http://www.w3.org/2000/09/xmldsig#", IsNullable=false)]
public partial class ObjectType {
    
    private System.Xml.XmlNode[] anyField;
    
    private string idField;
    
    private string mimeTypeField;
    
    private string encodingField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    [System.Xml.Serialization.XmlAnyElementAttribute()]
    public System.Xml.XmlNode[] Any {
        get {
            return this.anyField;
        }
        set {
            this.anyField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="ID")]
    public string Id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string MimeType {
        get {
            return this.mimeTypeField;
        }
        set {
            this.mimeTypeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
    public string Encoding {
        get {
            return this.encodingField;
        }
        set {
            this.encodingField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.w3.org/2000/09/xmldsig#")]
[System.Xml.Serialization.XmlRootAttribute("SPKIData", Namespace="http://www.w3.org/2000/09/xmldsig#", IsNullable=false)]
public partial class SPKIDataType {
    
    private byte[][] sPKISexpField;
    
    private System.Xml.XmlElement anyField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("SPKISexp", DataType="base64Binary")]
    public byte[][] SPKISexp {
        get {
            return this.sPKISexpField;
        }
        set {
            this.sPKISexpField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAnyElementAttribute()]
    public System.Xml.XmlElement Any {
        get {
            return this.anyField;
        }
        set {
            this.anyField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.w3.org/2000/09/xmldsig#")]
[System.Xml.Serialization.XmlRootAttribute("PGPData", Namespace="http://www.w3.org/2000/09/xmldsig#", IsNullable=false)]
public partial class PGPDataType {
    
    private object[] itemsField;
    
    private ItemsChoiceType1[] itemsElementNameField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAnyElementAttribute()]
    [System.Xml.Serialization.XmlElementAttribute("PGPKeyID", typeof(byte[]), DataType="base64Binary")]
    [System.Xml.Serialization.XmlElementAttribute("PGPKeyPacket", typeof(byte[]), DataType="base64Binary")]
    [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemsElementName")]
    public object[] Items {
        get {
            return this.itemsField;
        }
        set {
            this.itemsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ItemsElementName")]
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public ItemsChoiceType1[] ItemsElementName {
        get {
            return this.itemsElementNameField;
        }
        set {
            this.itemsElementNameField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.w3.org/2000/09/xmldsig#", IncludeInSchema=false)]
public enum ItemsChoiceType1 {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("##any:")]
    Item,
    
    /// <remarks/>
    PGPKeyID,
    
    /// <remarks/>
    PGPKeyPacket,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.w3.org/2000/09/xmldsig#")]
public partial class X509IssuerSerialType {
    
    private string x509IssuerNameField;
    
    private string x509SerialNumberField;
    
    /// <remarks/>
    public string X509IssuerName {
        get {
            return this.x509IssuerNameField;
        }
        set {
            this.x509IssuerNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
    public string X509SerialNumber {
        get {
            return this.x509SerialNumberField;
        }
        set {
            this.x509SerialNumberField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.w3.org/2000/09/xmldsig#")]
[System.Xml.Serialization.XmlRootAttribute("X509Data", Namespace="http://www.w3.org/2000/09/xmldsig#", IsNullable=false)]
public partial class X509DataType {
    
    private object[] itemsField;
    
    private ItemsChoiceType[] itemsElementNameField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAnyElementAttribute()]
    [System.Xml.Serialization.XmlElementAttribute("X509CRL", typeof(byte[]), DataType="base64Binary")]
    [System.Xml.Serialization.XmlElementAttribute("X509Certificate", typeof(byte[]), DataType="base64Binary")]
    [System.Xml.Serialization.XmlElementAttribute("X509IssuerSerial", typeof(X509IssuerSerialType))]
    [System.Xml.Serialization.XmlElementAttribute("X509SKI", typeof(byte[]), DataType="base64Binary")]
    [System.Xml.Serialization.XmlElementAttribute("X509SubjectName", typeof(string))]
    [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemsElementName")]
    public object[] Items {
        get {
            return this.itemsField;
        }
        set {
            this.itemsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ItemsElementName")]
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public ItemsChoiceType[] ItemsElementName {
        get {
            return this.itemsElementNameField;
        }
        set {
            this.itemsElementNameField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.w3.org/2000/09/xmldsig#", IncludeInSchema=false)]
public enum ItemsChoiceType {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("##any:")]
    Item,
    
    /// <remarks/>
    X509CRL,
    
    /// <remarks/>
    X509Certificate,
    
    /// <remarks/>
    X509IssuerSerial,
    
    /// <remarks/>
    X509SKI,
    
    /// <remarks/>
    X509SubjectName,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.w3.org/2000/09/xmldsig#")]
[System.Xml.Serialization.XmlRootAttribute("RetrievalMethod", Namespace="http://www.w3.org/2000/09/xmldsig#", IsNullable=false)]
public partial class RetrievalMethodType {
    
    private TransformType[] transformsField;
    
    private string uRIField;
    
    private string typeField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("Transform", IsNullable=false)]
    public TransformType[] Transforms {
        get {
            return this.transformsField;
        }
        set {
            this.transformsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
    public string URI {
        get {
            return this.uRIField;
        }
        set {
            this.uRIField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
    public string Type {
        get {
            return this.typeField;
        }
        set {
            this.typeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.w3.org/2000/09/xmldsig#")]
[System.Xml.Serialization.XmlRootAttribute("Transform", Namespace="http://www.w3.org/2000/09/xmldsig#", IsNullable=false)]
public partial class TransformType {
    
    private object[] itemsField;
    
    private string[] textField;
    
    private string algorithmField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAnyElementAttribute()]
    [System.Xml.Serialization.XmlElementAttribute("XPath", typeof(string))]
    public object[] Items {
        get {
            return this.itemsField;
        }
        set {
            this.itemsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string[] Text {
        get {
            return this.textField;
        }
        set {
            this.textField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
    public string Algorithm {
        get {
            return this.algorithmField;
        }
        set {
            this.algorithmField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.w3.org/2000/09/xmldsig#")]
[System.Xml.Serialization.XmlRootAttribute("RSAKeyValue", Namespace="http://www.w3.org/2000/09/xmldsig#", IsNullable=false)]
public partial class RSAKeyValueType {
    
    private byte[] modulusField;
    
    private byte[] exponentField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
    public byte[] Modulus {
        get {
            return this.modulusField;
        }
        set {
            this.modulusField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
    public byte[] Exponent {
        get {
            return this.exponentField;
        }
        set {
            this.exponentField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.w3.org/2000/09/xmldsig#")]
[System.Xml.Serialization.XmlRootAttribute("DSAKeyValue", Namespace="http://www.w3.org/2000/09/xmldsig#", IsNullable=false)]
public partial class DSAKeyValueType {
    
    private byte[] pField;
    
    private byte[] qField;
    
    private byte[] gField;
    
    private byte[] yField;
    
    private byte[] jField;
    
    private byte[] seedField;
    
    private byte[] pgenCounterField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
    public byte[] P {
        get {
            return this.pField;
        }
        set {
            this.pField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
    public byte[] Q {
        get {
            return this.qField;
        }
        set {
            this.qField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
    public byte[] G {
        get {
            return this.gField;
        }
        set {
            this.gField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
    public byte[] Y {
        get {
            return this.yField;
        }
        set {
            this.yField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
    public byte[] J {
        get {
            return this.jField;
        }
        set {
            this.jField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
    public byte[] Seed {
        get {
            return this.seedField;
        }
        set {
            this.seedField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
    public byte[] PgenCounter {
        get {
            return this.pgenCounterField;
        }
        set {
            this.pgenCounterField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.w3.org/2000/09/xmldsig#")]
[System.Xml.Serialization.XmlRootAttribute("KeyValue", Namespace="http://www.w3.org/2000/09/xmldsig#", IsNullable=false)]
public partial class KeyValueType {
    
    private object itemField;
    
    private string[] textField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAnyElementAttribute()]
    [System.Xml.Serialization.XmlElementAttribute("DSAKeyValue", typeof(DSAKeyValueType))]
    [System.Xml.Serialization.XmlElementAttribute("RSAKeyValue", typeof(RSAKeyValueType))]
    public object Item {
        get {
            return this.itemField;
        }
        set {
            this.itemField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string[] Text {
        get {
            return this.textField;
        }
        set {
            this.textField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.w3.org/2000/09/xmldsig#")]
[System.Xml.Serialization.XmlRootAttribute("KeyInfo", Namespace="http://www.w3.org/2000/09/xmldsig#", IsNullable=false)]
public partial class KeyInfoType {
    
    private object[] itemsField;
    
    private ItemsChoiceType2[] itemsElementNameField;
    
    private string[] textField;
    
    private string idField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAnyElementAttribute()]
    [System.Xml.Serialization.XmlElementAttribute("KeyName", typeof(string))]
    [System.Xml.Serialization.XmlElementAttribute("KeyValue", typeof(KeyValueType))]
    [System.Xml.Serialization.XmlElementAttribute("MgmtData", typeof(string))]
    [System.Xml.Serialization.XmlElementAttribute("PGPData", typeof(PGPDataType))]
    [System.Xml.Serialization.XmlElementAttribute("RetrievalMethod", typeof(RetrievalMethodType))]
    [System.Xml.Serialization.XmlElementAttribute("SPKIData", typeof(SPKIDataType))]
    [System.Xml.Serialization.XmlElementAttribute("X509Data", typeof(X509DataType))]
    [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemsElementName")]
    public object[] Items {
        get {
            return this.itemsField;
        }
        set {
            this.itemsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ItemsElementName")]
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public ItemsChoiceType2[] ItemsElementName {
        get {
            return this.itemsElementNameField;
        }
        set {
            this.itemsElementNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string[] Text {
        get {
            return this.textField;
        }
        set {
            this.textField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="ID")]
    public string Id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.w3.org/2000/09/xmldsig#", IncludeInSchema=false)]
public enum ItemsChoiceType2 {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("##any:")]
    Item,
    
    /// <remarks/>
    KeyName,
    
    /// <remarks/>
    KeyValue,
    
    /// <remarks/>
    MgmtData,
    
    /// <remarks/>
    PGPData,
    
    /// <remarks/>
    RetrievalMethod,
    
    /// <remarks/>
    SPKIData,
    
    /// <remarks/>
    X509Data,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.w3.org/2000/09/xmldsig#")]
[System.Xml.Serialization.XmlRootAttribute("SignatureValue", Namespace="http://www.w3.org/2000/09/xmldsig#", IsNullable=false)]
public partial class SignatureValueType {
    
    private string idField;
    
    private byte[] valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="ID")]
    public string Id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute(DataType="base64Binary")]
    public byte[] Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.w3.org/2000/09/xmldsig#")]
[System.Xml.Serialization.XmlRootAttribute("DigestMethod", Namespace="http://www.w3.org/2000/09/xmldsig#", IsNullable=false)]
public partial class DigestMethodType {
    
    private System.Xml.XmlNode[] anyField;
    
    private string algorithmField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    [System.Xml.Serialization.XmlAnyElementAttribute()]
    public System.Xml.XmlNode[] Any {
        get {
            return this.anyField;
        }
        set {
            this.anyField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
    public string Algorithm {
        get {
            return this.algorithmField;
        }
        set {
            this.algorithmField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.w3.org/2000/09/xmldsig#")]
[System.Xml.Serialization.XmlRootAttribute("Reference", Namespace="http://www.w3.org/2000/09/xmldsig#", IsNullable=false)]
public partial class ReferenceType {
    
    private TransformType[] transformsField;
    
    private DigestMethodType digestMethodField;
    
    private byte[] digestValueField;
    
    private string idField;
    
    private string uRIField;
    
    private string typeField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("Transform", IsNullable=false)]
    public TransformType[] Transforms {
        get {
            return this.transformsField;
        }
        set {
            this.transformsField = value;
        }
    }
    
    /// <remarks/>
    public DigestMethodType DigestMethod {
        get {
            return this.digestMethodField;
        }
        set {
            this.digestMethodField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
    public byte[] DigestValue {
        get {
            return this.digestValueField;
        }
        set {
            this.digestValueField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="ID")]
    public string Id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
    public string URI {
        get {
            return this.uRIField;
        }
        set {
            this.uRIField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
    public string Type {
        get {
            return this.typeField;
        }
        set {
            this.typeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.w3.org/2000/09/xmldsig#")]
[System.Xml.Serialization.XmlRootAttribute("SignatureMethod", Namespace="http://www.w3.org/2000/09/xmldsig#", IsNullable=false)]
public partial class SignatureMethodType {
    
    private string hMACOutputLengthField;
    
    private System.Xml.XmlNode[] anyField;
    
    private string algorithmField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
    public string HMACOutputLength {
        get {
            return this.hMACOutputLengthField;
        }
        set {
            this.hMACOutputLengthField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    [System.Xml.Serialization.XmlAnyElementAttribute()]
    public System.Xml.XmlNode[] Any {
        get {
            return this.anyField;
        }
        set {
            this.anyField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
    public string Algorithm {
        get {
            return this.algorithmField;
        }
        set {
            this.algorithmField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.w3.org/2000/09/xmldsig#")]
[System.Xml.Serialization.XmlRootAttribute("CanonicalizationMethod", Namespace="http://www.w3.org/2000/09/xmldsig#", IsNullable=false)]
public partial class CanonicalizationMethodType {
    
    private System.Xml.XmlNode[] anyField;
    
    private string algorithmField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    [System.Xml.Serialization.XmlAnyElementAttribute()]
    public System.Xml.XmlNode[] Any {
        get {
            return this.anyField;
        }
        set {
            this.anyField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
    public string Algorithm {
        get {
            return this.algorithmField;
        }
        set {
            this.algorithmField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.w3.org/2000/09/xmldsig#")]
[System.Xml.Serialization.XmlRootAttribute("SignedInfo", Namespace="http://www.w3.org/2000/09/xmldsig#", IsNullable=false)]
public partial class SignedInfoType {
    
    private CanonicalizationMethodType canonicalizationMethodField;
    
    private SignatureMethodType signatureMethodField;
    
    private ReferenceType[] referenceField;
    
    private string idField;
    
    /// <remarks/>
    public CanonicalizationMethodType CanonicalizationMethod {
        get {
            return this.canonicalizationMethodField;
        }
        set {
            this.canonicalizationMethodField = value;
        }
    }
    
    /// <remarks/>
    public SignatureMethodType SignatureMethod {
        get {
            return this.signatureMethodField;
        }
        set {
            this.signatureMethodField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Reference")]
    public ReferenceType[] Reference {
        get {
            return this.referenceField;
        }
        set {
            this.referenceField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="ID")]
    public string Id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.w3.org/2000/09/xmldsig#")]
[System.Xml.Serialization.XmlRootAttribute("Signature", Namespace="http://www.w3.org/2000/09/xmldsig#", IsNullable=false)]
public partial class SignatureType {
    
    private SignedInfoType signedInfoField;
    
    private SignatureValueType signatureValueField;
    
    private KeyInfoType keyInfoField;
    
    private ObjectType[] objectField;
    
    private string idField;
    
    /// <remarks/>
    public SignedInfoType SignedInfo {
        get {
            return this.signedInfoField;
        }
        set {
            this.signedInfoField = value;
        }
    }
    
    /// <remarks/>
    public SignatureValueType SignatureValue {
        get {
            return this.signatureValueField;
        }
        set {
            this.signatureValueField = value;
        }
    }
    
    /// <remarks/>
    public KeyInfoType KeyInfo {
        get {
            return this.keyInfoField;
        }
        set {
            this.keyInfoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Object")]
    public ObjectType[] Object {
        get {
            return this.objectField;
        }
        set {
            this.objectField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="ID")]
    public string Id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class maquinaFiscal {
    
    private string marcaField;
    
    private string modeloField;
    
    private string serieField;
    
    /// <remarks/>
    public string marca {
        get {
            return this.marcaField;
        }
        set {
            this.marcaField = value;
        }
    }
    
    /// <remarks/>
    public string modelo {
        get {
            return this.modeloField;
        }
        set {
            this.modeloField = value;
        }
    }
    
    /// <remarks/>
    public string serie {
        get {
            return this.serieField;
        }
        set {
            this.serieField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class tipoNegociable {
    
    private string correoField;
    
    /// <remarks/>
    public string correo {
        get {
            return this.correoField;
        }
        set {
            this.correoField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class impuesto {
    
    private string codigoField;
    
    private string codigoPorcentajeField;
    
    private decimal tarifaField;
    
    private decimal baseImponibleField;
    
    private decimal valorField;
    
    /// <remarks/>
    public string codigo {
        get {
            return this.codigoField;
        }
        set {
            this.codigoField = value;
        }
    }
    
    /// <remarks/>
    public string codigoPorcentaje {
        get {
            return this.codigoPorcentajeField;
        }
        set {
            this.codigoPorcentajeField = value;
        }
    }
    
    /// <remarks/>
    public decimal tarifa {
        get {
            return this.tarifaField;
        }
        set {
            this.tarifaField = value;
        }
    }
    
    /// <remarks/>
    public decimal baseImponible {
        get {
            return this.baseImponibleField;
        }
        set {
            this.baseImponibleField = value;
        }
    }
    
    /// <remarks/>
    public decimal valor {
        get {
            return this.valorField;
        }
        set {
            this.valorField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class compensacion {
    
    private string codigoField;
    
    private decimal tarifaField;
    
    private decimal valorField;
    
    /// <remarks/>
    public string codigo {
        get {
            return this.codigoField;
        }
        set {
            this.codigoField = value;
        }
    }
    
    /// <remarks/>
    public decimal tarifa {
        get {
            return this.tarifaField;
        }
        set {
            this.tarifaField = value;
        }
    }
    
    /// <remarks/>
    public decimal valor {
        get {
            return this.valorField;
        }
        set {
            this.valorField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class facturaInfoFactura {
    
    private string fechaEmisionField;
    
    private string dirEstablecimientoField;
    
    private string contribuyenteEspecialField;
    
    private obligadoContabilidad obligadoContabilidadField;
    
    private bool obligadoContabilidadFieldSpecified;
    
    private string comercioExteriorField;
    
    private string incoTermFacturaField;
    
    private string lugarIncoTermField;
    
    private string paisOrigenField;
    
    private string puertoEmbarqueField;
    
    private string puertoDestinoField;
    
    private string paisDestinoField;
    
    private string paisAdquisicionField;
    
    private string tipoIdentificacionCompradorField;
    
    private string guiaRemisionField;
    
    private string razonSocialCompradorField;
    
    private string identificacionCompradorField;
    
    private string direccionCompradorField;
    
    private decimal totalSinImpuestosField;
    
    private decimal totalSubsidioField;
    
    private bool totalSubsidioFieldSpecified;
    
    private string incoTermTotalSinImpuestosField;
    
    private decimal totalDescuentoField;
    
    private string codDocReembolsoField;
    
    private decimal totalComprobantesReembolsoField;
    
    private bool totalComprobantesReembolsoFieldSpecified;
    
    private decimal totalBaseImponibleReembolsoField;
    
    private bool totalBaseImponibleReembolsoFieldSpecified;
    
    private decimal totalImpuestoReembolsoField;
    
    private bool totalImpuestoReembolsoFieldSpecified;
    
    private facturaInfoFacturaTotalImpuesto[] totalConImpuestosField;
    
    private compensacion[] compensacionesField;
    
    private decimal propinaField;
    
    private bool propinaFieldSpecified;
    
    private decimal fleteInternacionalField;
    
    private bool fleteInternacionalFieldSpecified;
    
    private decimal seguroInternacionalField;
    
    private bool seguroInternacionalFieldSpecified;
    
    private decimal gastosAduanerosField;
    
    private bool gastosAduanerosFieldSpecified;
    
    private decimal gastosTransporteOtrosField;
    
    private bool gastosTransporteOtrosFieldSpecified;
    
    private decimal importeTotalField;
    
    private string monedaField;
    
    private string placaField;
    
    private pagosPago[] pagosField;
    
    private decimal valorRetIvaField;
    
    private bool valorRetIvaFieldSpecified;
    
    private decimal valorRetRentaField;
    
    private bool valorRetRentaFieldSpecified;
    
    /// <remarks/>
    public string fechaEmision {
        get {
            return this.fechaEmisionField;
        }
        set {
            this.fechaEmisionField = value;
        }
    }
    
    /// <remarks/>
    public string dirEstablecimiento {
        get {
            return this.dirEstablecimientoField;
        }
        set {
            this.dirEstablecimientoField = value;
        }
    }
    
    /// <remarks/>
    public string contribuyenteEspecial {
        get {
            return this.contribuyenteEspecialField;
        }
        set {
            this.contribuyenteEspecialField = value;
        }
    }
    
    /// <remarks/>
    public obligadoContabilidad obligadoContabilidad {
        get {
            return this.obligadoContabilidadField;
        }
        set {
            this.obligadoContabilidadField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool obligadoContabilidadSpecified {
        get {
            return this.obligadoContabilidadFieldSpecified;
        }
        set {
            this.obligadoContabilidadFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public string comercioExterior {
        get {
            return this.comercioExteriorField;
        }
        set {
            this.comercioExteriorField = value;
        }
    }
    
    /// <remarks/>
    public string incoTermFactura {
        get {
            return this.incoTermFacturaField;
        }
        set {
            this.incoTermFacturaField = value;
        }
    }
    
    /// <remarks/>
    public string lugarIncoTerm {
        get {
            return this.lugarIncoTermField;
        }
        set {
            this.lugarIncoTermField = value;
        }
    }
    
    /// <remarks/>
    public string paisOrigen {
        get {
            return this.paisOrigenField;
        }
        set {
            this.paisOrigenField = value;
        }
    }
    
    /// <remarks/>
    public string puertoEmbarque {
        get {
            return this.puertoEmbarqueField;
        }
        set {
            this.puertoEmbarqueField = value;
        }
    }
    
    /// <remarks/>
    public string puertoDestino {
        get {
            return this.puertoDestinoField;
        }
        set {
            this.puertoDestinoField = value;
        }
    }
    
    /// <remarks/>
    public string paisDestino {
        get {
            return this.paisDestinoField;
        }
        set {
            this.paisDestinoField = value;
        }
    }
    
    /// <remarks/>
    public string paisAdquisicion {
        get {
            return this.paisAdquisicionField;
        }
        set {
            this.paisAdquisicionField = value;
        }
    }
    
    /// <remarks/>
    public string tipoIdentificacionComprador {
        get {
            return this.tipoIdentificacionCompradorField;
        }
        set {
            this.tipoIdentificacionCompradorField = value;
        }
    }
    
    /// <remarks/>
    public string guiaRemision {
        get {
            return this.guiaRemisionField;
        }
        set {
            this.guiaRemisionField = value;
        }
    }
    
    /// <remarks/>
    public string razonSocialComprador {
        get {
            return this.razonSocialCompradorField;
        }
        set {
            this.razonSocialCompradorField = value;
        }
    }
    
    /// <remarks/>
    public string identificacionComprador {
        get {
            return this.identificacionCompradorField;
        }
        set {
            this.identificacionCompradorField = value;
        }
    }
    
    /// <remarks/>
    public string direccionComprador {
        get {
            return this.direccionCompradorField;
        }
        set {
            this.direccionCompradorField = value;
        }
    }
    
    /// <remarks/>
    public decimal totalSinImpuestos {
        get {
            return this.totalSinImpuestosField;
        }
        set {
            this.totalSinImpuestosField = value;
        }
    }
    
    /// <remarks/>
    public decimal totalSubsidio {
        get {
            return this.totalSubsidioField;
        }
        set {
            this.totalSubsidioField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool totalSubsidioSpecified {
        get {
            return this.totalSubsidioFieldSpecified;
        }
        set {
            this.totalSubsidioFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public string incoTermTotalSinImpuestos {
        get {
            return this.incoTermTotalSinImpuestosField;
        }
        set {
            this.incoTermTotalSinImpuestosField = value;
        }
    }
    
    /// <remarks/>
    public decimal totalDescuento {
        get {
            return this.totalDescuentoField;
        }
        set {
            this.totalDescuentoField = value;
        }
    }
    
    /// <remarks/>
    public string codDocReembolso {
        get {
            return this.codDocReembolsoField;
        }
        set {
            this.codDocReembolsoField = value;
        }
    }
    
    /// <remarks/>
    public decimal totalComprobantesReembolso {
        get {
            return this.totalComprobantesReembolsoField;
        }
        set {
            this.totalComprobantesReembolsoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool totalComprobantesReembolsoSpecified {
        get {
            return this.totalComprobantesReembolsoFieldSpecified;
        }
        set {
            this.totalComprobantesReembolsoFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public decimal totalBaseImponibleReembolso {
        get {
            return this.totalBaseImponibleReembolsoField;
        }
        set {
            this.totalBaseImponibleReembolsoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool totalBaseImponibleReembolsoSpecified {
        get {
            return this.totalBaseImponibleReembolsoFieldSpecified;
        }
        set {
            this.totalBaseImponibleReembolsoFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public decimal totalImpuestoReembolso {
        get {
            return this.totalImpuestoReembolsoField;
        }
        set {
            this.totalImpuestoReembolsoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool totalImpuestoReembolsoSpecified {
        get {
            return this.totalImpuestoReembolsoFieldSpecified;
        }
        set {
            this.totalImpuestoReembolsoFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("totalImpuesto", IsNullable=false)]
    public facturaInfoFacturaTotalImpuesto[] totalConImpuestos {
        get {
            return this.totalConImpuestosField;
        }
        set {
            this.totalConImpuestosField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
    public compensacion[] compensaciones {
        get {
            return this.compensacionesField;
        }
        set {
            this.compensacionesField = value;
        }
    }
    
    /// <remarks/>
    public decimal propina {
        get {
            return this.propinaField;
        }
        set {
            this.propinaField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool propinaSpecified {
        get {
            return this.propinaFieldSpecified;
        }
        set {
            this.propinaFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public decimal fleteInternacional {
        get {
            return this.fleteInternacionalField;
        }
        set {
            this.fleteInternacionalField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool fleteInternacionalSpecified {
        get {
            return this.fleteInternacionalFieldSpecified;
        }
        set {
            this.fleteInternacionalFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public decimal seguroInternacional {
        get {
            return this.seguroInternacionalField;
        }
        set {
            this.seguroInternacionalField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool seguroInternacionalSpecified {
        get {
            return this.seguroInternacionalFieldSpecified;
        }
        set {
            this.seguroInternacionalFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public decimal gastosAduaneros {
        get {
            return this.gastosAduanerosField;
        }
        set {
            this.gastosAduanerosField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool gastosAduanerosSpecified {
        get {
            return this.gastosAduanerosFieldSpecified;
        }
        set {
            this.gastosAduanerosFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public decimal gastosTransporteOtros {
        get {
            return this.gastosTransporteOtrosField;
        }
        set {
            this.gastosTransporteOtrosField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool gastosTransporteOtrosSpecified {
        get {
            return this.gastosTransporteOtrosFieldSpecified;
        }
        set {
            this.gastosTransporteOtrosFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public decimal importeTotal {
        get {
            return this.importeTotalField;
        }
        set {
            this.importeTotalField = value;
        }
    }
    
    /// <remarks/>
    public string moneda {
        get {
            return this.monedaField;
        }
        set {
            this.monedaField = value;
        }
    }
    
    /// <remarks/>
    public string placa {
        get {
            return this.placaField;
        }
        set {
            this.placaField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("pago", IsNullable=false)]
    public pagosPago[] pagos {
        get {
            return this.pagosField;
        }
        set {
            this.pagosField = value;
        }
    }
    
    /// <remarks/>
    public decimal valorRetIva {
        get {
            return this.valorRetIvaField;
        }
        set {
            this.valorRetIvaField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool valorRetIvaSpecified {
        get {
            return this.valorRetIvaFieldSpecified;
        }
        set {
            this.valorRetIvaFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public decimal valorRetRenta {
        get {
            return this.valorRetRentaField;
        }
        set {
            this.valorRetRentaField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool valorRetRentaSpecified {
        get {
            return this.valorRetRentaFieldSpecified;
        }
        set {
            this.valorRetRentaFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
public enum obligadoContabilidad {
    
    /// <remarks/>
    SI,
    
    /// <remarks/>
    NO,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class facturaInfoFacturaTotalImpuesto {
    
    private string codigoField;
    
    private string codigoPorcentajeField;
    
    private decimal descuentoAdicionalField;
    
    private bool descuentoAdicionalFieldSpecified;
    
    private decimal baseImponibleField;
    
    private decimal tarifaField;
    
    private bool tarifaFieldSpecified;
    
    private decimal valorField;
    
    private decimal valorDevolucionIvaField;
    
    private bool valorDevolucionIvaFieldSpecified;
    
    /// <remarks/>
    public string codigo {
        get {
            return this.codigoField;
        }
        set {
            this.codigoField = value;
        }
    }
    
    /// <remarks/>
    public string codigoPorcentaje {
        get {
            return this.codigoPorcentajeField;
        }
        set {
            this.codigoPorcentajeField = value;
        }
    }
    
    /// <remarks/>
    public decimal descuentoAdicional {
        get {
            return this.descuentoAdicionalField;
        }
        set {
            this.descuentoAdicionalField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool descuentoAdicionalSpecified {
        get {
            return this.descuentoAdicionalFieldSpecified;
        }
        set {
            this.descuentoAdicionalFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public decimal baseImponible {
        get {
            return this.baseImponibleField;
        }
        set {
            this.baseImponibleField = value;
        }
    }
    
    /// <remarks/>
    public decimal tarifa {
        get {
            return this.tarifaField;
        }
        set {
            this.tarifaField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool tarifaSpecified {
        get {
            return this.tarifaFieldSpecified;
        }
        set {
            this.tarifaFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public decimal valor {
        get {
            return this.valorField;
        }
        set {
            this.valorField = value;
        }
    }
    
    /// <remarks/>
    public decimal valorDevolucionIva {
        get {
            return this.valorDevolucionIvaField;
        }
        set {
            this.valorDevolucionIvaField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool valorDevolucionIvaSpecified {
        get {
            return this.valorDevolucionIvaFieldSpecified;
        }
        set {
            this.valorDevolucionIvaFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class pagosPago {
    
    private string formaPagoField;
    
    private decimal totalField;
    
    private decimal plazoField;
    
    private bool plazoFieldSpecified;
    
    private string unidadTiempoField;
    
    /// <remarks/>
    public string formaPago {
        get {
            return this.formaPagoField;
        }
        set {
            this.formaPagoField = value;
        }
    }
    
    /// <remarks/>
    public decimal total {
        get {
            return this.totalField;
        }
        set {
            this.totalField = value;
        }
    }
    
    /// <remarks/>
    public decimal plazo {
        get {
            return this.plazoField;
        }
        set {
            this.plazoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool plazoSpecified {
        get {
            return this.plazoFieldSpecified;
        }
        set {
            this.plazoFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public string unidadTiempo {
        get {
            return this.unidadTiempoField;
        }
        set {
            this.unidadTiempoField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class facturaDetalle {
    
    private string codigoPrincipalField;
    
    private string codigoAuxiliarField;
    
    private string descripcionField;
    
    private string unidadMedidaField;
    
    private decimal cantidadField;
    
    private decimal precioUnitarioField;
    
    private decimal precioSinSubsidioField;
    
    private bool precioSinSubsidioFieldSpecified;
    
    private decimal descuentoField;
    
    private decimal precioTotalSinImpuestoField;
    
    private facturaDetalleDetAdicional[] detallesAdicionalesField;
    
    private impuesto[] impuestosField;
    
    /// <remarks/>
    public string codigoPrincipal {
        get {
            return this.codigoPrincipalField;
        }
        set {
            this.codigoPrincipalField = value;
        }
    }
    
    /// <remarks/>
    public string codigoAuxiliar {
        get {
            return this.codigoAuxiliarField;
        }
        set {
            this.codigoAuxiliarField = value;
        }
    }
    
    /// <remarks/>
    public string descripcion {
        get {
            return this.descripcionField;
        }
        set {
            this.descripcionField = value;
        }
    }
    
    /// <remarks/>
    public string unidadMedida {
        get {
            return this.unidadMedidaField;
        }
        set {
            this.unidadMedidaField = value;
        }
    }
    
    /// <remarks/>
    public decimal cantidad {
        get {
            return this.cantidadField;
        }
        set {
            this.cantidadField = value;
        }
    }
    
    /// <remarks/>
    public decimal precioUnitario {
        get {
            return this.precioUnitarioField;
        }
        set {
            this.precioUnitarioField = value;
        }
    }
    
    /// <remarks/>
    public decimal precioSinSubsidio {
        get {
            return this.precioSinSubsidioField;
        }
        set {
            this.precioSinSubsidioField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool precioSinSubsidioSpecified {
        get {
            return this.precioSinSubsidioFieldSpecified;
        }
        set {
            this.precioSinSubsidioFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public decimal descuento {
        get {
            return this.descuentoField;
        }
        set {
            this.descuentoField = value;
        }
    }
    
    /// <remarks/>
    public decimal precioTotalSinImpuesto {
        get {
            return this.precioTotalSinImpuestoField;
        }
        set {
            this.precioTotalSinImpuestoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("detAdicional", IsNullable=false)]
    public facturaDetalleDetAdicional[] detallesAdicionales {
        get {
            return this.detallesAdicionalesField;
        }
        set {
            this.detallesAdicionalesField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
    public impuesto[] impuestos {
        get {
            return this.impuestosField;
        }
        set {
            this.impuestosField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class facturaDetalleDetAdicional {
    
    private string nombreField;
    
    private string valorField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string nombre {
        get {
            return this.nombreField;
        }
        set {
            this.nombreField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string valor {
        get {
            return this.valorField;
        }
        set {
            this.valorField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class reembolsosReembolsoDetalle {
    
    private string tipoIdentificacionProveedorReembolsoField;
    
    private string identificacionProveedorReembolsoField;
    
    private string codPaisPagoProveedorReembolsoField;
    
    private string tipoProveedorReembolsoField;
    
    private string codDocReembolsoField;
    
    private string estabDocReembolsoField;
    
    private string ptoEmiDocReembolsoField;
    
    private string secuencialDocReembolsoField;
    
    private string fechaEmisionDocReembolsoField;
    
    private string numeroautorizacionDocReembField;
    
    private detalleImpuestosDetalleImpuesto[] detalleImpuestosField;
    
    private compensacion[] compensacionesReembolsoField;
    
    /// <remarks/>
    public string tipoIdentificacionProveedorReembolso {
        get {
            return this.tipoIdentificacionProveedorReembolsoField;
        }
        set {
            this.tipoIdentificacionProveedorReembolsoField = value;
        }
    }
    
    /// <remarks/>
    public string identificacionProveedorReembolso {
        get {
            return this.identificacionProveedorReembolsoField;
        }
        set {
            this.identificacionProveedorReembolsoField = value;
        }
    }
    
    /// <remarks/>
    public string codPaisPagoProveedorReembolso {
        get {
            return this.codPaisPagoProveedorReembolsoField;
        }
        set {
            this.codPaisPagoProveedorReembolsoField = value;
        }
    }
    
    /// <remarks/>
    public string tipoProveedorReembolso {
        get {
            return this.tipoProveedorReembolsoField;
        }
        set {
            this.tipoProveedorReembolsoField = value;
        }
    }
    
    /// <remarks/>
    public string codDocReembolso {
        get {
            return this.codDocReembolsoField;
        }
        set {
            this.codDocReembolsoField = value;
        }
    }
    
    /// <remarks/>
    public string estabDocReembolso {
        get {
            return this.estabDocReembolsoField;
        }
        set {
            this.estabDocReembolsoField = value;
        }
    }
    
    /// <remarks/>
    public string ptoEmiDocReembolso {
        get {
            return this.ptoEmiDocReembolsoField;
        }
        set {
            this.ptoEmiDocReembolsoField = value;
        }
    }
    
    /// <remarks/>
    public string secuencialDocReembolso {
        get {
            return this.secuencialDocReembolsoField;
        }
        set {
            this.secuencialDocReembolsoField = value;
        }
    }
    
    /// <remarks/>
    public string fechaEmisionDocReembolso {
        get {
            return this.fechaEmisionDocReembolsoField;
        }
        set {
            this.fechaEmisionDocReembolsoField = value;
        }
    }
    
    /// <remarks/>
    public string numeroautorizacionDocReemb {
        get {
            return this.numeroautorizacionDocReembField;
        }
        set {
            this.numeroautorizacionDocReembField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("detalleImpuesto", IsNullable=false)]
    public detalleImpuestosDetalleImpuesto[] detalleImpuestos {
        get {
            return this.detalleImpuestosField;
        }
        set {
            this.detalleImpuestosField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("compensacionReembolso", IsNullable=false)]
    public compensacion[] compensacionesReembolso {
        get {
            return this.compensacionesReembolsoField;
        }
        set {
            this.compensacionesReembolsoField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class detalleImpuestosDetalleImpuesto {
    
    private string codigoField;
    
    private string codigoPorcentajeField;
    
    private decimal tarifaField;
    
    private decimal baseImponibleReembolsoField;
    
    private decimal impuestoReembolsoField;
    
    /// <remarks/>
    public string codigo {
        get {
            return this.codigoField;
        }
        set {
            this.codigoField = value;
        }
    }
    
    /// <remarks/>
    public string codigoPorcentaje {
        get {
            return this.codigoPorcentajeField;
        }
        set {
            this.codigoPorcentajeField = value;
        }
    }
    
    /// <remarks/>
    public decimal tarifa {
        get {
            return this.tarifaField;
        }
        set {
            this.tarifaField = value;
        }
    }
    
    /// <remarks/>
    public decimal baseImponibleReembolso {
        get {
            return this.baseImponibleReembolsoField;
        }
        set {
            this.baseImponibleReembolsoField = value;
        }
    }
    
    /// <remarks/>
    public decimal impuestoReembolso {
        get {
            return this.impuestoReembolsoField;
        }
        set {
            this.impuestoReembolsoField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class facturaCampoAdicional {
    
    private string nombreField;
    
    private string valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string nombre {
        get {
            return this.nombreField;
        }
        set {
            this.nombreField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public enum facturaID {
    
    /// <remarks/>
    comprobante,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.w3.org/2000/09/xmldsig#")]
[System.Xml.Serialization.XmlRootAttribute("Transforms", Namespace="http://www.w3.org/2000/09/xmldsig#", IsNullable=false)]
public partial class TransformsType {
    
    private TransformType[] transformField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Transform")]
    public TransformType[] Transform {
        get {
            return this.transformField;
        }
        set {
            this.transformField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.w3.org/2000/09/xmldsig#")]
[System.Xml.Serialization.XmlRootAttribute("Manifest", Namespace="http://www.w3.org/2000/09/xmldsig#", IsNullable=false)]
public partial class ManifestType {
    
    private ReferenceType[] referenceField;
    
    private string idField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Reference")]
    public ReferenceType[] Reference {
        get {
            return this.referenceField;
        }
        set {
            this.referenceField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="ID")]
    public string Id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.w3.org/2000/09/xmldsig#")]
[System.Xml.Serialization.XmlRootAttribute("SignatureProperties", Namespace="http://www.w3.org/2000/09/xmldsig#", IsNullable=false)]
public partial class SignaturePropertiesType {
    
    private SignaturePropertyType[] signaturePropertyField;
    
    private string idField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("SignatureProperty")]
    public SignaturePropertyType[] SignatureProperty {
        get {
            return this.signaturePropertyField;
        }
        set {
            this.signaturePropertyField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="ID")]
    public string Id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.w3.org/2000/09/xmldsig#")]
[System.Xml.Serialization.XmlRootAttribute("SignatureProperty", Namespace="http://www.w3.org/2000/09/xmldsig#", IsNullable=false)]
public partial class SignaturePropertyType {
    
    private System.Xml.XmlElement[] itemsField;
    
    private string[] textField;
    
    private string targetField;
    
    private string idField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAnyElementAttribute()]
    public System.Xml.XmlElement[] Items {
        get {
            return this.itemsField;
        }
        set {
            this.itemsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string[] Text {
        get {
            return this.textField;
        }
        set {
            this.textField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
    public string Target {
        get {
            return this.targetField;
        }
        set {
            this.targetField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="ID")]
    public string Id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
}
